Update pytest section to tool:pytest
jhuapl-boss/ndingest pull request #9
Opened 2019-04-08 20:06 UTC by lrodri29

Unit test clean up. 

Work in Progress: Need to figure out one more test failure here before merging.

2019-04-09 13:36 UTC, movestill requested changes

2019-04-09 13:36 UTC, movestill commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
I looked at the test. If this method wasn't implemented, you would get an exception.

2019-04-09 13:36 UTC, movestill commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
On line 83, change the suffix from `_dead_letter` to `-dlq` and the test should passed. I changed the suffix when we were in a rush and must not have run the tests, afterwards. :ashamed:

2019-04-09 13:37 UTC, lrodri29 commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
@movestill I will try that again, however I must say I did try `-dlq` as well as `-index-dlq` and the test continued to fail
I will try it again though, I was making the changes locally and copying them to the endpoint instance so maybe I missed the copy step on one of those tests. I'll report back.

2019-04-09 13:40 UTC, movestill commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
Worked for me on master branch.

2019-04-09 13:42 UTC, lrodri29 commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
Oh alright, Awesome! I must have not copied it when I was testing. Thanks!

2019-04-09 13:52 UTC, lrodri29 commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
Tested. Resolving Conversation :)

2019-04-09 16:17 UTC, movestill requested changes

2019-04-09 16:17 UTC, movestill commented on test/test_deadletter_queue.py
> +    @unittest.skip("generateBossQueueName() not implemented")
Still need to remove the `skip`.

2019-04-09 16:19 UTC, movestill approved these changes

2019-04-11 22:06 UTC, sandyhider approved these changes

2019-04-11 22:06 UTC, merged